name: Verify Bundle
on: [ push, pull_request ]

jobs:
  verify-bundle:
    name: Verify Distribution Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Check Distribution
        uses: tetchel/bundle-verifier-action@v0.0.2
        with:
          bundle_file: dist/index.js
          bundle_command: "npm run bundle"
